//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProgNew.rc
//
#define IDW_STATUS_BAR                  101
#define IDD_PROGNEW_DIALOG              102
#define ID_A                            103
#define ID_B                            104
#define ID_C                            105
#define ID_D                            106
#define IDW_TOOL_BAR                    107
#define ID_GRAPHICS_WND                 111
#define IDW_STATUS_BAR_VIEW             112
#define IDC_BUTTON_COMMENTS             113
#define IDR_MAINFRAME                   128
#define IDR_BITMAPTOOLBAR               130
#define IDD_REGION_WND                  141
#define IDD_DIALOG_PARAM_REGION         142
#define IDD_DLG_KE_END                  143
#define IDB_BITMAP_ICONFORREG           145
#define IDI_ICON_FOR_REG                147
#define IDI_ICON_FOR_REG_NULL           149
#define IDD_DLG_MEASURE_OPT             150
#define IDD_DLG_SETTINGS_FOR_CURVERS    152
#define IDD_DLG_VIEWER_SET              153
#define IDI_ICON_FOR_REG_ONOFF          155
#define IDD_DLG_FI_TABLE                156
#define IDD_DIALOG_COMMENTS_EDIT        159
#define IDD_DLG_DXPS                    160
#define IDD_DIALOG_PARAM_DXPS           161
#define IDR_MENU_DXPS_POPUP             162
#define IDB_BITMAP_OFF                  164
#define IDB_BITMAP_CUR                  168
#define IDB_BITMAP_DEF                  169
#define IDD_DLG_ABOUT                   171
#define IDI_ICON_DXPS                   172
#define IDI_ICON_XPS                    173
#define IDD_DLG_HARDWARE                174
#define IDD_DLG_COUNTER                 176
#define IDC_LIST_REGION                 1000
#define IDC_BUTTON_ADDNEW               1001
#define IDC_BUTTON_DELETE               1002
#define IDC_BUTTON_EDIT                 1003
#define IDC_BUTTON_ONOFF                1005
#define IDC_BUTTON_VIEW                 1006
#define IDC_BUTTON_UP                   1007
#define IDC_BUTTON_DOWN                 1008
#define IDC_BUTTON_COPY                 1009
#define IDC_REPORT_REGION               1010
#define IDC_STATIC_PARAM_HV             1015
#define IDC_STATIC_PARAM_KE_BEGIN       1016
#define IDC_STATIC_PARAM_KE_END         1017
#define IDC_STATIC_PARAM_STEP           1018
#define IDC_STATIC_PARAM_N              1019
#define IDC_STATIC_PARAM_STEP2          1019
#define IDC_STATIC_PARAM_TIME           1020
#define IDC_STATIC_PARAM_COMMENTS       1021
#define IDC_STATIC_PARAM_HV1            1022
#define IDC_EDIT_HV                     1023
#define IDC_STATIC_PARAM_KE_END2        1024
#define IDC_EDIT_KE_BEGIN               1025
#define IDC_STATIC_HV                   1026
#define IDC_STATIC_KE_BEGIN             1027
#define IDC_STATIC_KE_END               1028
#define IDC_STATIC_STEP                 1029
#define IDC_STATIC_N                    1030
#define IDC_STATIC_STEP2                1030
#define IDC_STATIC_TIME                 1031
#define IDC_STATIC_STEP3                1031
#define IDC_STATIC_COMMENTS             1032
#define IDC_STATIC_STEP4                1032
#define IDC_EDIT_KE_END                 1033
#define IDC_STATIC_COMMENTS2            1033
#define IDC_EDIT_STEP                   1034
#define IDC_STATIC_STEP5                1034
#define IDC_EDIT_N                      1035
#define IDC_EDIT_DXPSPAR_DIVISOR        1035
#define IDC_EDIT_TIME                   1036
#define IDC_EDIT_DXPSPAR_DIVIDENT       1036
#define IDC_EDIT_COMMENTS               1037
#define IDC_EDIT_DXPSPAR_DWELL          1037
#define IDC_STATIC_PARAM                1038
#define IDC_EDIT_DXPSPAR_HV             1038
#define IDC_STATIC_KEBE                 1039
#define IDC_EDIT_DXPSPAR_COMMENTS       1039
#define IDC_STATIC_ANODE                1040
#define IDC_RADIO_BIG                   1041
#define IDC_STATIC_ONOFF                1041
#define IDC_RADIO                       1042
#define IDC_RADIO_SMALL                 1042
#define IDC_STATIC_ANODE2               1042
#define IDC_EDIT_KE_END2                1042
#define IDC_EDIT_PRIORITY               1042
#define IDC_STATIC_CAPTION              1043
#define IDC_EDIT_DXPSPAR_DELAY          1043
#define IDC_STATIC_KE_END2              1043
#define IDC_RADIO_OVER                  1044
#define IDC_STATIC_COMMENTS3            1044
#define IDC_STATIC_BORDER               1045
#define IDC_STATIC_PARAM_KE_END3        1045
#define IDC_STATIC_BIG                  1046
#define IDC_EDIT_PRIORITY2              1046
#define IDC_EDIT_MAKE_COPY_AT           1046
#define IDC_STATIC_SMALL                1047
#define IDC_STATIC_CAPTION_BIG          1049
#define IDC_STATIC_CAPTION_SMALL        1050
#define IDC_STATIC_CURRENT              1061
#define IDC_STATIC_CURR_LINE            1062
#define IDC_CHECK_CURR_LINE             1063
#define IDC_STATIC_CURR_POINTS          1064
#define IDC_CHECK_CURR_POINTS           1065
#define IDC_STATIC_CURR_LINE3           1066
#define IDC_EDIT_CURR_SIZE_OF_POINTS    1067
#define IDC_STATIC_CURR_SAMPLE          1068
#define IDC_EDIT_CURR_SAMPLE            1069
#define IDC_BUTTON_CURR_COLOR           1070
#define IDC_STATIC_RESULT               1071
#define IDC_STATIC_RES_LINE             1072
#define IDC_CHECK_RES_LINE              1073
#define IDC_STATIC_RES_POINTS           1074
#define IDC_CHECK_RES_POINTS            1075
#define IDC_STATIC_CURR_LINE6           1076
#define IDC_EDIT_RES_SIZE_OF_POINTS     1077
#define IDC_STATIC_GRID                 1077
#define IDC_STATIC_CURR_SAMPLE2         1078
#define IDC_STATIC_FONT                 1078
#define IDC_EDIT_RES_SAMPLE             1079
#define IDC_BUTTON_RES_COLOR            1080
#define IDC_STATIC_RES                  1081
#define IDC_STATIC_CURR                 1082
#define IDC_COMBO_SIZE_CURR             1083
#define IDC_COMBO_SIZE_CURR2            1084
#define IDC_COMBO_SIZE_RES              1084
#define IDC_STATIC_CURVE                1084
#define IDC_STATIC_GRID_GRID            1085
#define IDC_CHECK_GRID                  1086
#define IDC_STATIC_CURVE_LINE           1087
#define IDC_STATIC_CURVE_POINTS         1088
#define IDC_STATIC_CURVE_SAMPLE         1089
#define IDC_EDIT_CURVE_SAMPLE           1090
#define IDC_STATIC_CURVE_LINE3          1091
#define IDC_STATIC_GRID_SAMPLE          1092
#define IDC_EDIT_GRID_SAMPLE            1093
#define IDC_BUTTON_GRID_COLOR           1094
#define IDC_STATIC_GRID_SAMPLE2         1095
#define IDC_EDIT_CURSOR_SAMPLE          1095
#define IDC_EDIT_FONT_SAMPLE            1096
#define IDC_BUTTON_FONT_COLOR           1097
#define IDC_STATIC_CURVE_SIZE           1098
#define IDC_COMBO_SIZE_CURVE            1099
#define IDC_CHECK_CURVE_LINE            1100
#define IDC_CHECK_CURVE_POINTS          1101
#define IDC_BUTTON_CURVE_COLOR          1102
#define IDC_FI_LIST                     1104
#define IDC_BUTTON_HV_TABLE             1105
#define IDC_RADIO_KE                    1106
#define IDC_RADIO_BE                    1107
#define IDC_STATIC_KE_BE                1108
#define IDC_STATIC_ANODE_TXT            1109
#define IDC_COMBO_ANODE                 1110
#define IDC_RADIO_ON                    1111
#define IDC_COMBO_DXPSPAR_HV            1111
#define IDC_RADIO_OFF                   1112
#define IDC_COMBO_COLOR                 1112
#define IDC_STATIC_ONOFF_TXT            1113
#define IDC_COMBO_DXPSPAR_DIVIDENT      1113
#define IDC_BUTTON_RESET                1114
#define IDC_COMBO_DXPSPAR_DIVISOR       1114
#define IDC_COMBO_HV                    1115
#define IDC_BUTTON_RESET2               1116
#define IDC_BUTTON_RESET_ALL            1116
#define IDC_BUTTON_COMMENTS_EDIT        1117
#define IDC_EDIT                        1118
#define IDC_BUTTON_DXPS_ONOFF           1119
#define IDC_BUTTON_DXPS_EDIT            1120
#define IDC_BUTTON_DXPS_VIEW            1121
#define IDC_EDIT_DXPS_TIME              1122
#define IDC_LIST_DXPS                   1123
#define IDC_STATIC_SCAN_T               1124
#define IDC_CHECK_REMEASURE             1125
#define IDC_BUTTON_DXPS_ADDNEW          1125
#define IDC_RADIO_DXPSPAR_ON            1126
#define IDC_BUTTON_DXPS_DELETE          1126
#define IDC_RADIO_DXPSPAR_OFF           1127
#define IDC_EDIT_DXPS_DWELL_TIME        1127
#define IDC_STATIC_SCAN_T2              1128
#define IDC_STATIC_DWELL_T              1128
#define IDC_RADIO_DXPSPAR_TYPE_BE       1129
#define IDC_RADIO_DXPSPAR_TYPE_DIV      1130
#define IDC_EDIT_DXPSPAR_BE             1131
#define IDC_BUTTON_DXPSPAR_HV_TABLE     1132
#define IDC_BUTTON_DXPSPAR_RESET        1133
#define IDC_BUTTON_DXPSPAR_RESET_ALL    1133
#define IDC_GROUP_NSIGMA                1134
#define IDC_BUTTON_DXPSPAR_RESET_REG    1134
#define IDC_GROUP_ATTEMPTS              1135
#define IDC_STATIC_NSIGMA_MIN           1136
#define IDC_STATIC_NSIGMA_MAX           1137
#define IDC_STATIC_ATTEMPTS_MIN         1138
#define IDC_STATIC_ATTEMPTS_MAX         1139
#define IDC_CHECK_GUIDE_LINES           1140
#define IDC_STATIC_FILE_DATE            1141
#define IDC_BUTTON_DXPS_CLOSE           1142
#define IDC_STATIC_BUILD_DATE           1142
#define IDC_STATIC_MODE                 1143
#define IDC_EDIT_RETARD_CALIBRATION     1144
#define IDD_CAM_SETUP_DLG               1145
#define IDC_STATIC_VER                  1145
#define IDD_CAM_SETUP_HP_DLG            1146
#define IDC_COUNTER_MODULE_NAME         1146
#define IDC_EDIT_CRATE_NUM              1147
#define IDC_RUN_MODE                    1147
#define IDC_EDIT_REGIST_POS             1148
#define IDC_COOLING_OK                  1148
#define IDC_EDIT_COUNT_POS              1149
#define IDC_BUTTON_APPLY                1149
#define IDC_EDIT_TIMER_POS              1150
#define IDC_MODULE_AVAILABLE            1150
#define IDC_EDIT_REGIST_TEST            1151
#define IDC_COM_PORT                    1151
#define IDC_TEST                        1152
#define IDC_COUNT_TIME                  1152
#define IDC_EDIT_CRATE_TEST             1153
#define IDC_DETECT_THRESHOLD            1153
#define IDC_EDIT_COUNT_TEST             1154
#define IDC_COOLING_THRESHOLD           1154
#define IDC_EDIT_TIMER_TEST             1155
#define IDC_PORT_AVAILABLE              1155
#define IDC_EDIT_HP_CRATE_NUM           1156
#define IDC_EDIT_HP_REGIST_POS          1157
#define IDC_EDIT_HP_REGIST_RETARD_POS   1158
#define IDC_EDIT_HP_COUNT_POS           1159
#define IDC_EDIT_HP_TIMER_POS           1160
#define IDC_MODULE_CONFIGURED           1160
#define IDC_EDIT_HP_REGIST_TEST         1161
#define IDC_DXPS_HIDE_OFF               1161
#define IDC_CHECK_DXPS_HIDE_OFF         1161
#define IDC_EDIT_HP_REGIST_RETARD_TEST  1162
#define IDC_STATIC_BEGIN_TIME           1162
#define IDC_BUTTON_HP_TEST              1163
#define IDC_STATIC_BEGIN_TIME2          1163
#define IDC_STATIC_END_TIME             1163
#define IDC_EDIT_HP_CRATE_TEST          1164
#define IDC_STATIC_LAST_EDIT_TIME       1164
#define IDC_EDIT_HP_COUNT_TEST          1165
#define IDC_EDIT_HP_TIMER_TEST          1166
#define IDC_STATIC_CUR_COUNT_TIME       1166
#define IDC_EDIT_HP_REGIST_HV_POS       1167
#define IDC_EDIT_HP_REGIST_HV_TEST      1168
#define IDC_STATIC_CUR_DETECT_THRESHOLD 1170
#define IDC_STATIC_CUR_INTERLOCK_THRESHOLD 1171
#define IDC_STATIC_CUR_COOLING_FREQ     1172
#define IDC_SLIDER_NSIGMA               2001
#define IDC_SLIDER_NATTEMPTS            2002
#define IDC_SLIDER_NSUBMEASURINGS       2003
#define IDC_SLIDER_REGIONDELAY          2004
#define IDC_STATIC_NSIGMA               2005
#define IDC_STATIC_ATTEMPTS             2006
#define IDC_STATIC_SUBMEASURINGS        2007
#define IDC_STATIC_REGIONDELAY          2008
#define ID_FILE_REGIONS                 32772
#define ID_FILE_NEW_PROJECT             32773
#define ID_FILE_OPEN_PROJECT            32774
#define ID_FILE_SAVE_PROJECT            32775
#define ID_FILE_SAVE_PROJECT_AS         32776
#define ID_FILE_SAVE_AS_EASYPLOT        32777
#define ID_FILE_EXIT                    32778
#define ID_PROGRAM_REGION_TABLE         32779
#define ID_PROGRAMM_START               32780
#define ID_PROGRAMM_PAUSE               32781
#define ID_PROGRAMM_STOP                32781
#define ID_SETTINGS_CAMAC_SETUP         32782
#define ID_SETTINGS_MEASURING_OPTIONS   32783
#define ID_GRAPHICS_FONT                32784
#define ID_GRAPHICS_DRAW_GRAPH          32785
#define ID_GRAPHICS_COLOR               32786
#define ID_GRAPHICS_GRID                32787
#define ID_GRAPHICS_SETTINGS_FOR_CURVERS 32788
#define ID_GRAPHICS_SETTINGS_FOR_VIEWER 32789
#define ID_FILE_SAVE_AS_EASYPLOT_MC     32790
#define ID_SETTINGS_FITABLE             32791
#define ID_FILE_SAVE_AS_ORIGIN          32793
#define ID_PROGRAM_DXPS_TABLE           32794
#define ID_PROGRAM_START_DXPS           32795
#define ID_ROOT_ADDNEW                  32796
#define ID_ROOT_EDIT                    32797
#define ID_ROOT_DELETE                  32798
#define ID_ROOT_VIEW                    32799
#define ID_ROOT_ONOFF                   32800
#define ID_ABOUT                        32801
#define ID_SETTINGS_HARDWARESETUP       32802
#define ID_FILE_RECENTFILES_NOFILES     32803
#define ID_FILE_RECENTPROJECTS_NOFILES  32803
#define ID_FILE_RECENTPROJECTS_FILE1    32804
#define ID_FILE_RECENTPROJECTS_FILE2    32805
#define ID_FILE_RECENTPROJECTS_FILE3    32806
#define ID_FILE_RECENTPROJECTS_FILE4    32807
#define ID_SETTINGS_COUNTERSETUP        32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1165
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
